spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:${dbPort}/lonessum?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dbUsername}
    password: ${dbPassword}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true